"""Guard the committed SANDBOX side-panel artifacts (browser-extension/sandbox/
launchpad.html + launchpad-init.js + live_council.html), generated by
scripts/build_extension_sidepanel.py.

The gap this closes (2026-07-14 review catch): `test_extension_launchpad_build`
pins browser-extension/launchpad.html against the template, but NOTHING pinned
the sandbox copies — so the 07-14 council_review verdict-copy fix ("the answer
you'd have picked" → "the one to trust here", the chairman-transmission-null
scrub) shipped in the Python source while the committed extension sidebar kept
serving the retired claim, and the eval-card removal left ~350 lines of dead
eval sections in sandbox/launchpad.html. A copy change in council_review.py or
launchpad_template.py must not be able to leave the extension stale again.
Regenerate with `python scripts/build_extension_sidepanel.py`.
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SANDBOX = REPO / "browser-extension" / "sandbox"


def _builders():
    scripts = str(REPO / "scripts")
    if scripts not in sys.path:
        sys.path.insert(0, scripts)
    import build_extension_sidepanel

    return build_extension_sidepanel


def test_committed_sandbox_launchpad_in_sync():
    """sandbox/launchpad.html + launchpad-init.js must equal a fresh build —
    else the side panel ships a stale UI (the exact rot class that carried the
    retired verdict copy + dead eval sections until 2026-07-14)."""
    mod = _builders()
    html, init_js = mod.build()
    committed_html = (SANDBOX / "launchpad.html").read_text(encoding="utf-8")
    committed_init = (SANDBOX / "launchpad-init.js").read_text(encoding="utf-8")
    assert committed_html == html, (
        "browser-extension/sandbox/launchpad.html drifted from the template — "
        "run `python scripts/build_extension_sidepanel.py` and commit."
    )
    assert committed_init == init_js, (
        "browser-extension/sandbox/launchpad-init.js drifted from the template — "
        "run `python scripts/build_extension_sidepanel.py` and commit."
    )


def test_committed_sandbox_live_council_in_sync():
    """sandbox/live_council.html must equal a fresh render of
    council_review.render_live_council_page() — the sidebar's council page is a
    committed artifact, so a verdict-copy change in council_review.py silently
    strands it otherwise."""
    mod = _builders()
    council = mod.build_council()
    committed = (SANDBOX / "live_council.html").read_text(encoding="utf-8")
    assert committed == council, (
        "browser-extension/sandbox/live_council.html drifted from "
        "council_review.py — run `python scripts/build_extension_sidepanel.py` "
        "and commit."
    )
