"""Harness output must never be read as the person's behaviour.

WHY THIS EXISTS. The disagreement ledger's entire claim is that a verdict reflects what
the PERSON did next: it retrieves their prompts in the 14 days after a council and asks
which branch their later work took. But `trust --build` dispatches its resolver prompt
through `claude -p`, that transcript is ingested as role=user, and the NEXT build
retrieves those prompts as evidence of behaviour.

Measured 2026-07-26, before the fix:

    evidence rows fed to the resolver : 2,314
      machine-generated               :   859  (37.1%)
    claims with >=1 machine row       :   185 of 294  (62.9%)
    claims resolved on machine ONLY   :    37

The system was reading its own output as its input, inside the one layer described as
behaviour-validated, and every build deepened the loop. 188 verdicts were invalidated
and re-resolved behind this filter.

The two guards that matter here are the two that are easy to get wrong:
  * the filter must catch the machine shapes actually present in the corpus, AND
  * it must NOT eat a human who happens to use the same words. The security-hook rule is
    deliberately gated on the co-occurring file manifest for exactly that reason — a
    person can legitimately type "review this change for security vulnerabilities".
"""
from __future__ import annotations

import pytest

from trinity_local.ingest import is_user_facing_text

MACHINE = [
    ("A technical decision was contested. The contested claim:  CLAIM: Is provider auth "
     "the actual launch blocker?", "trinity's OWN ledger resolver — the recursion"),
    ('<subagent_notification> {"agent_path":"019e7f5b","status":{"completed":"No"}}',
     "subagent notification envelope"),
    ("<local-command-caveat>Caveat: The messages below were generated by the user while "
     "running local commands.", "local command caveat"),
    ("UX-DESIGNER LOOP. Spawn the `ux-designer` subagent via the Task tool and have it "
     "drive the real UI.", "/loop driver, 607 copies"),
    ("Review this change for security vulnerabilities.  Changed files (you may Read "
     "these and any other file in the repo):", "security-review hook, 1748 copies"),
]

HUMAN = [
    ("review this change for security vulnerabilities please, I am worried about the "
     "auth path we discussed", "a HUMAN using the hook's words, without its manifest"),
    ("can we update this embeddings flow to not rely on verdict capture? That is "
     "connecting multiple transcripts", "genuine technical turn"),
    ("We went and signed the trust docs at the meeting that was scheduled. I already "
     "moved 1M to the fund.", "genuine personal turn"),
    ("what is the current state of the buildings, is it progressing on schedule",
     "genuine short question"),
    ("A technical decision I made last week turned out wrong, can we revisit",
     "human sentence that merely STARTS similarly to the resolver prompt"),
]


class TestMachineShapesAreDropped:
    @pytest.mark.parametrize("text,label", MACHINE, ids=[m[1][:34] for m in MACHINE])
    def test_machine_text_is_filtered(self, text, label):
        assert is_user_facing_text(text) is False, (
            f"machine shape leaked into the corpus as user behaviour: {label}"
        )


class TestHumanTextSurvives:
    """The expensive failure mode is the opposite one. A filter that eats the person's
    own words corrupts the lens and the ledger in a way no test would notice, because
    everything downstream would still look clean."""

    @pytest.mark.parametrize("text,label", HUMAN, ids=[h[1][:34] for h in HUMAN])
    def test_human_text_is_kept(self, text, label):
        assert is_user_facing_text(text) is True, (
            f"the filter ate a genuine human turn: {label}"
        )

    def test_the_hook_rule_needs_its_manifest_not_just_its_words(self):
        """Mutation-sensitive by construction: drop the `changed files` co-occurrence
        from the rule and this pair stops discriminating."""
        hookish = "Review this change for security vulnerabilities."
        real_hook = hookish + "  Changed files (you may Read these):  src/a.py"
        assert is_user_facing_text(real_hook) is False
        assert is_user_facing_text(
            hookish + " I think the token handling is wrong and want a second opinion."
        ) is True


class TestLedgerEvidenceAppliesIt:
    def test_assemble_evidence_excludes_machine_turns(self):
        """The load-bearing wire. `_load_nodes` reads prompt_nodes raw, so the filter
        has to be applied at evidence-assembly time or the ledger keeps grading its own
        homework. Asserted on the RETURNED evidence, not on the filter in isolation."""
        import datetime

        import numpy as np

        from trinity_local.disagreement_ledger import DisagreementPattern, assemble_evidence

        t0 = datetime.datetime(2026, 7, 1, tzinfo=datetime.timezone.utc)
        pat = DisagreementPattern(
            claim_id="c1", council_id="cn1", at=t0.isoformat(),
            claim="provider auth is the launch blocker",
            why_matters="it decides the launch order",
            providers_for=["claude"], providers_against=["codex"],
            chairman_winner="claude", task_excerpt="",
        )
        vec = np.ones(8, dtype=np.float32) / np.sqrt(8)
        nodes = [
            (t0 + datetime.timedelta(days=1),
             "A technical decision was contested. The contested claim:  CLAIM: auth", vec),
            (t0 + datetime.timedelta(days=2),
             "we shipped the auth fix and the launch order held up fine", vec),
        ]
        out = assemble_evidence([pat], nodes, lambda xs: [[1.0] * 8 for _ in xs])
        texts = [r["text"] for r in out["c1"]]
        assert not any(t.startswith("A technical decision was contested") for t in texts), (
            f"the resolver's OWN prompt was returned as the user's behaviour: {texts}"
        )
        assert any("we shipped the auth fix" in t for t in texts), (
            "the genuine follow-up turn must survive the filter"
        )
